#!/bin/sh
set -eu
[ "$(id -u)" -eq 0 ] || exit 1
[ "$#" -eq 4 ] || [ "$#" -eq 5 ] || {
  echo 'usage: install-nginx.sh <domain> <backend-port> <platform-port> <web-port> [admin-port]' >&2
  exit 64
}
domain=$1
# The assets are this script's own neighbours, resolved from its location
# rather than from the caller's. Before the move they were named relative to
# the repository root, so the script worked only when an operator happened to
# be standing in it.
here=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
admin_port=${5:-}
environment_file=/etc/ai-agent/environment
allowlist_source=/etc/ai-agent/admin-staging-allowed-cidrs
ingress_fragment=/etc/nginx/ai-agent-admin-ingress.conf
routes_file=/etc/nginx/ai-agent-proxy-routes.conf
site_file=/etc/nginx/sites-available/ai-agent
printf '%s' "$domain" | grep -Eq '^[A-Za-z0-9.-]+$' || exit 64
for port in "$2" "$3" "$4" ${admin_port:+"$admin_port"}; do
  printf '%s' "$port" | grep -Eq '^[0-9]{2,5}$' || exit 64
  [ "$port" -le 65535 ] || exit 64
done

# One trusted address range per line, and nothing that can mean "everyone".
#
# Validated field by field rather than by one pattern: an `allow` directive
# nginx cannot parse makes the entire configuration invalid, and one it parses
# differently than intended would widen the allowlist without saying so.
#
# Two things are refused outright in both families -- a `/0` prefix and the
# unspecified address -- because between them they are every way to write "the
# internet". Beyond that the range is the operator's business: how narrow an
# allowlist should be is not a decision this script is in a position to make,
# and refusing a legitimate `fc00::/7` in the name of caution would only send
# somebody looking for a way around it.
valid_cidr() {
  value=$1
  address=${value%%/*}
  prefix=
  case $value in */*) prefix=${value#*/} ;; esac

  # `0.0.0.0` and `::` match everything a mask is applied to, so no prefix
  # makes them a restriction.
  case $address in
    0.0.0.0 | ::) return 1 ;;
  esac

  case $address in
    *:*)
      printf '%s' "$address" | grep -Eq '^[0-9A-Fa-f]*(:[0-9A-Fa-f]*)+$' || return 1
      # At most one `::`, which is what makes the shape check above mean
      # anything; nginx parses the groups themselves.
      [ "$(printf '%s' "$address" | awk -F'::' '{ print NF - 1 }')" -le 1 ] ||
        return 1
      # Required for IPv6: a bare address here is far more likely to be a
      # truncated range than an intended single host.
      [ -n "$prefix" ] || return 1
      printf '%s' "$prefix" | grep -Eq '^[0-9]{1,3}$' || return 1
      [ "$prefix" -ge 1 ] || return 1
      [ "$prefix" -le 128 ] || return 1
      ;;
    *)
      printf '%s' "$address" | grep -Eq '^[0-9]{1,3}(\.[0-9]{1,3}){3}$' || return 1
      for octet in $(printf '%s' "$address" | tr '.' ' '); do
        [ "$octet" -le 255 ] || return 1
      done
      if [ -n "$prefix" ]; then
        printf '%s' "$prefix" | grep -Eq '^[0-9]{1,2}$' || return 1
        [ "$prefix" -ge 1 ] || return 1
        [ "$prefix" -le 32 ] || return 1
      fi
      ;;
  esac

  return 0
}

# Fail closed, in every direction.
#
# A missing allowlist, an empty one, and one holding only comments all render
# the same fragment: `deny all;` and nothing else. The route still exists and
# still refuses everybody, which is the safe end of the two -- leaving the
# route out instead would send `/admin` to the public site, and leaving the
# fragment out would make every `include` of it a configuration error.
#
# A malformed entry is refused rather than skipped. Skipping one would mean an
# operator's typo silently removed their own access, and the next person to
# look would find a route that denies everyone for no visible reason.
render_ingress_fragment() {
  destination=$1
  allowed=0

  {
    echo '# Generated by infra/gateway/nginx/install-nginx.sh. Do not edit.'
    echo "# Source: $allowlist_source"
    echo '#'
    echo '# Ingress restriction, not authorization: the Control Plane authorizes'
    echo '# every administrative request from the session, and an allowlisted'
    echo '# address is not a permission.'
  } >"$destination"

  if [ -r "$allowlist_source" ]; then
    while IFS= read -r line || [ -n "$line" ]; do
      entry=$(printf '%s' "$line" | tr -d '[:space:]')
      case $entry in '' | '#'*) continue ;; esac

      valid_cidr "$entry" || {
        echo "administrative allowlist entry is not a usable address range: $entry" >&2
        return 1
      }

      printf 'allow %s;\n' "$entry" >>"$destination"
      allowed=$((allowed + 1))
    done <"$allowlist_source"
  fi

  # Last, and unconditional. `allow`/`deny` are evaluated in order and the
  # first match wins, so this is what makes the list above an allowlist rather
  # than a preference.
  echo 'deny all;' >>"$destination"

  if [ "$allowed" -eq 0 ]; then
    echo "note: no administrative client ranges configured in $allowlist_source" >&2
    echo 'note: /admin is installed and refuses every client until one is added' >&2
  fi

  return 0
}

install -d -o root -g root -m 0755 /var/www/letsencrypt /etc/nginx/snippets \
  /etc/nginx/sites-available /etc/nginx/sites-enabled
install -o root -g root -m 0644 "$here/snippets/proxy-common.conf" /etc/nginx/snippets/ai-agent-proxy-common.conf

staging_area=$(mktemp -d)
trap 'rm -rf "$staging_area"' EXIT HUP INT TERM

sed -e "s/__BACKEND_PORT__/$2/g" -e "s/__PLATFORM_PORT__/$3/g" -e "s/__WEB_PORT__/$4/g" \
  "$here/templates/proxy-routes.conf.template" >"$staging_area/routes.conf"

if [ -n "$admin_port" ]; then
  # Staging only, decided from the host's own recorded environment rather than
  # from what the caller asked for. A production host cannot install this
  # route by passing the argument.
  environment=$(sed -n '1p' "$environment_file" 2>/dev/null || true)
  [ "$environment" = staging ] || {
    echo 'the administrative route is installed on staging hosts only' >&2
    echo "host environment: ${environment:-unset}" >&2
    exit 64
  }

  render_ingress_fragment "$staging_area/admin-ingress.conf" || exit 64
  sed -e "s/__ADMIN_PORT__/$admin_port/g" \
    "$here/templates/admin-route.conf.template" >>"$staging_area/routes.conf"
fi

# Everything above only staged files. From here the live configuration is
# replaced, so the previous one is kept until `nginx -t` has accepted the new
# one: a gateway that fails to validate must be the gateway it already was,
# not a half-written one waiting for the next unrelated reload to load it.
backup=$staging_area/previous
install -d -m 0700 "$backup"
[ ! -f "$routes_file" ] || cp "$routes_file" "$backup/routes.conf"
[ ! -f "$ingress_fragment" ] || cp "$ingress_fragment" "$backup/admin-ingress.conf"
[ ! -f "$site_file" ] || cp "$site_file" "$backup/site.conf"

restore() {
  if [ -f "$backup/routes.conf" ]; then
    install -o root -g root -m 0644 "$backup/routes.conf" "$routes_file"
  else
    rm -f "$routes_file"
  fi
  if [ -f "$backup/admin-ingress.conf" ]; then
    install -o root -g root -m 0644 "$backup/admin-ingress.conf" "$ingress_fragment"
  else
    rm -f "$ingress_fragment"
  fi
  if [ -f "$backup/site.conf" ]; then
    install -o root -g root -m 0644 "$backup/site.conf" "$site_file"
  fi
}

install -o root -g root -m 0644 "$staging_area/routes.conf" "$routes_file"
if [ -n "$admin_port" ]; then
  install -o root -g root -m 0644 "$staging_area/admin-ingress.conf" "$ingress_fragment"
else
  # No administrative route means no fragment to include, and a stale one left
  # behind would be an allowlist nothing reads.
  rm -f "$ingress_fragment"
fi

site=$staging_area/site.conf
sed "s/__DOMAIN__/$domain/g" "$here/templates/site-http.conf.template" >"$site"
# The HTTPS server block lives in the same file, and this is the script an
# operator re-runs to change the routes. Writing only the redirect would take a
# certificated host off 443 until somebody re-ran the certificate script. So
# the block is regenerated here too, from the same template
# issue-certificate.sh renders, whenever the certificate it names is actually
# present -- and never invented for a host that has none.
if [ -f "/etc/letsencrypt/live/$domain/fullchain.pem" ]; then
  sed "s/__DOMAIN__/$domain/g" "$here/templates/site-https.conf.template" >>"$site"
fi
install -o root -g root -m 0644 "$site" "$site_file"
ln -sfn /etc/nginx/sites-available/ai-agent /etc/nginx/sites-enabled/ai-agent
nginx -t || {
  restore
  echo 'nginx refused the generated configuration; the previous one is still installed' >&2
  exit 64
}
systemctl reload nginx
